#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-mapping}"

export BUDDYBOT_PREFLIGHT_CHECK="${BUDDYBOT_PREFLIGHT_CHECK:-0}"
export BUDDYBOT_ENABLE_MIC_LISTENER="${BUDDYBOT_ENABLE_MIC_LISTENER:-0}"
export BUDDYBOT_ENABLE_PI_SPEAKER="${BUDDYBOT_ENABLE_PI_SPEAKER:-0}"
export BUDDYBOT_CAMERA_WIDTH="${BUDDYBOT_CAMERA_WIDTH:-320}"
export BUDDYBOT_CAMERA_HEIGHT="${BUDDYBOT_CAMERA_HEIGHT:-240}"
export BUDDYBOT_CAMERA_FPS="${BUDDYBOT_CAMERA_FPS:-10}"
export BUDDYBOT_CAMERA_PUBLISH_RATE="${BUDDYBOT_CAMERA_PUBLISH_RATE:-5}"
export BUDDYBOT_CAMERA_START_DELAY="${BUDDYBOT_CAMERA_START_DELAY:-10}"
export BUDDYBOT_LIDAR_SETTLE_DELAY="${BUDDYBOT_LIDAR_SETTLE_DELAY:-10}"
export BUDDYBOT_CAMERA_PIXEL_FORMAT="${BUDDYBOT_CAMERA_PIXEL_FORMAT:-MJPG}"
export BUDDYBOT_CAMERA_BUFFER_SIZE="${BUDDYBOT_CAMERA_BUFFER_SIZE:-1}"

echo "[presentation] mode: $MODE"
echo "[presentation] preflight: $BUDDYBOT_PREFLIGHT_CHECK"
echo "[presentation] microphone listener: $BUDDYBOT_ENABLE_MIC_LISTENER"
echo "[presentation] pi speaker: $BUDDYBOT_ENABLE_PI_SPEAKER"
echo "[presentation] camera: ${BUDDYBOT_CAMERA_WIDTH}x${BUDDYBOT_CAMERA_HEIGHT} @ ${BUDDYBOT_CAMERA_FPS}fps publish ${BUDDYBOT_CAMERA_PUBLISH_RATE}Hz format ${BUDDYBOT_CAMERA_PIXEL_FORMAT}"
echo "[presentation] startup delays: lidar ${BUDDYBOT_LIDAR_SETTLE_DELAY}s camera ${BUDDYBOT_CAMERA_START_DELAY}s"

exec bash "$ROOT_DIR/scripts/run_demo_debug_bundle.sh" "$MODE"
